### PR TITLE
Add initial server

### PR DESCRIPTION
**Pull request by kamicut**
Adds the initial server and backing database.
Allows to query all features within a tile, using both pbf and geojson.

### CODE REVIEW

**Comment by kamicut** [comment]
@drewbo 
1. We can create arbitrary bbox queries if we need to. I was even thinking for efficiency purpose we should adjust the bbox queries to ask for surrounding tiles and cache them either on the server or the frontend layer
2. No, they're not clipped, it returns the full geometries, so we should figure out some way to cache them in case it's a lot of data over the wire

**Comment by drewbo** [comment]
1. 👍 probably fine cc: @dereklieu to confirm
2. This is preferable (so we don't try to overwrite things in the db with partial geometries) but agree with caching if it gets too large (let's not overinvest in this early)

**Comment by kamicut** [comment]
Discussion moved to #5 @dereklieu

**Comment by dereklieu** [comment]
👍

**Pull request merged**
